CREATE TABLE personagens_mortes(
   id          INTEGER  NOT NULL PRIMARY KEY 
  ,name        VARCHAR(33) NOT NULL
  ,allegiances VARCHAR(15) NOT NULL
  ,gender      VARCHAR(6) NOT NULL
  ,nobility    BOOLEAN  NOT NULL
  ,death_year  INTEGER  NOT NULL
);
INSERT INTO personagens_mortes(id,name,allegiances,gender,nobility,death_year) VALUES
 (1,'Addam Marbrand','Lannister','male',true,0)
,(2,'Aegon Frey (Jinglebell)','None','male',true,299)
,(3,'Aegon Targaryen','House Targaryen','male',true,0)
,(4,'Adrack Humble','House Greyjoy','male',true,300)
,(5,'Aemon Costayne','Lannister','male',true,0)
,(6,'Aemon Estermont','Baratheon','male',true,0)
,(7,'Aemon Targaryen (son of Maekar I)','Night''s Watch','male',true,300)
,(8,'Aenys Frey','None','female',true,300)
,(9,'Aeron Greyjoy','House Greyjoy','male',true,0)
,(10,'Aethan','Night''s Watch','male',false,0)
,(11,'Aggar','House Greyjoy','male',false,299)
,(12,'Aggo','House Targaryen','male',false,0)
,(13,'Alan of Rosby','Night''s Watch','male',true,300)
,(14,'Alayaya','None','female',false,0)
,(15,'Albar Royce','Arryn','male',true,0)
,(16,'Albett','Night''s Watch','male',false,0)
,(17,'Alebelly','House Stark','male',false,299)
,(18,'Alerie Hightower','House Tyrell','female',true,0)
,(19,'Alesander Staedmon','Baratheon','male',true,0)
,(20,'Alester Florent','Baratheon','male',true,300)
,(21,'Alia of Braavos','None','female',false,0)
,(22,'Alla Tyrell','House Tyrell','female',true,0)
,(23,'Allard Seaworth','Baratheon','male',true,299)
,(24,'Alliser Thorne','Night''s Watch','male',false,0)
,(25,'Alyn','House Stark','male',false,298)
,(26,'Alyn Ambrose','Tyrell','male',true,0)
,(27,'Alyn Estermont','Baratheon','male',true,0)
,(28,'Alyn Stackspear','Lannister','male',true,0)
,(29,'Alys Karstark','Stark','female',true,0)
,(30,'Alysane Mormont','Stark','female',true,0)
,(31,'Alyx Frey','None','male',true,0)
,(32,'Ambrode','Greyjoy','male',false,0)
,(33,'Amory Lorch','House Lannister','male',true,299)
,(34,'Andar Royce','Arryn','male',true,0)
,(35,'Andrew Estermont','Baratheon','male',true,0)
,(36,'Andrey Dalt','Martell','male',true,0)
,(37,'Andrik','Greyjoy','male',true,0)
,(38,'Anguy','None','male',false,0)
,(39,'Antario Jast','Lannister','male',true,0)
,(40,'Anvil Ryn','None','male',false,299)
,(41,'Anya Waynwood','Arryn','female',true,0)
,(42,'Archibald Yronwood','Martell','male',true,0)
,(43,'Ardrian Celtigar','Baratheon','male',true,0)
,(44,'Areo Hotah','House Martell','male',false,0)
,(45,'Arianne Martell','House Martell','female',true,0)
,(46,'Arneld','Lannister','male',false,0)
,(47,'Arnolf Karstark','Stark','male',true,0)
,(48,'Aron Santagar','Lannister','male',true,299)
,(49,'Arron','Night''s Watch','male',false,0)
,(50,'Arron Qorgyle','Martell','male',true,0)
,(51,'Arryk (Guard)','House Tyrell','male',false,0)
,(52,'Arson','Wildling','male',false,0)
,(53,'Arthor Karstark','Stark','male',true,0)
,(54,'Arwyn Frey','None','female',true,0)
,(55,'Arwyn Oakheart','Tyrell','female',true,0)
,(56,'Arya Stark','Stark','female',true,0)
,(57,'Arys Oakheart','Lannister','male',true,300)
,(58,'Asha Greyjoy','House Greyjoy','female',true,0)
,(59,'Aurane Waters','Lannister','male',false,0)
,(60,'Axell Florent','Baratheon','male',true,0)
,(61,'Azzak','None','male',true,0)
,(62,'Ballabar','Lannister','male',false,0)
,(63,'Balon Swann','Lannister','male',true,0)
,(64,'Bannen','Night''s Watch','male',false,299)
,(65,'Barbrey Dustin','Stark','female',true,0)
,(66,'Barra','None','female',false,299)
,(67,'Barristan Selmy','Targaryen','male',true,0)
,(68,'Barsena','None','female',false,300)
,(69,'Barth (brewer)','House Stark','male',false,0)
,(70,'Bass','Night''s Watch','male',false,0)
,(71,'Bayard Norcross','Tyrell','male',true,0)
,(72,'Bearded Ben','Night''s Watch','male',false,0)
,(73,'Becca','House Arryn','female',false,0)
,(74,'Becca the Baker','None','female',false,299)
,(75,'Bedwyck','Night''s Watch','male',false,0)
,(76,'Belaquo','None','male',false,0)
,(77,'Bella','None','female',false,0)
,(78,'Bellegere Otherys (courtesan)','None','female',true,0)
,(79,'Bellonara Otherys','None','female',true,0)
,(80,'Belwas','House Targaryen','male',false,0)
,(81,'Ben','None','male',false,0)
,(82,'Ben Bones','None','male',false,0)
,(83,'Ben Plumm','None','male',false,0)
,(84,'Benedar Belmore','Arryn','male',true,0)
,(85,'Benfred Tallhart','Stark','male',true,299)
,(86,'Benfrey Frey','None','male',true,299)
,(87,'Benjen Stark','Night''s Watch','male',true,298)
,(88,'Bennet','None','male',false,300)
,(89,'Beric Dondarrion','None','male',true,300)
,(90,'Bessa (Winterfell)','Stark','female',false,0)
,(91,'Beth Cassel','Stark','female',true,0)
,(92,'Bhakaz zo Loraq','None','male',true,0)
,(93,'Big Boil','Wildling','male',false,0)
,(94,'Big Walder Frey','None','male',true,0)
,(95,'Biter','None','male',false,300)
,(96,'Black Bernarr','Night''s Watch','male',false,0)
,(97,'Black Walder Frey','None','male',true,0)
,(98,'Blane','Night''s Watch','male',false,0)
,(99,'Bloodbeard','None','male',false,0)
,(100,'Blue Bard','House Tyrell','male',false,0)
,(101,'Bonifer Hasty','Lannister','male',true,0)
,(102,'Borcas','Night''s Watch','male',false,0)
,(103,'Boremund Harlaw','Greyjoy','male',true,0)
,(104,'Boros Blount','Baratheon','male',true,0)
,(105,'Borroq','Wildling','male',false,0)
,(106,'Bowen Marsh','Night''s Watch','male',false,0)
,(107,'Bran Stark','House Stark','male',true,0)
,(108,'Brandon Norrey','Stark','male',true,0)
,(109,'Brenett','None','male',false,0)
,(110,'Brienne of Tarth','Stark','female',true,0)
,(111,'Bronn','Lannister','male',true,0)
,(112,'Brown Bernarr','Night''s Watch','male',false,299)
,(113,'Brusco','None','male',false,0)
,(114,'Bryan Fossoway','Baratheon','male',true,299)
,(115,'Bryce Caron','Baratheon','male',true,299)
,(116,'Bryen','None','male',false,0)
,(117,'Bryen Farring','Baratheon','male',true,300)
,(118,'Brynden Rivers','House Targaryen','male',true,0)
,(119,'Brynden Tully','House Tully','male',true,0)
,(120,'Burton Crakehall','Lannister','male',true,299)
,(121,'Butterbumps','House Tyrell','male',false,0)
,(122,'Byam Flint','Night''s Watch','male',false,299)
,(123,'Byan Votyris','None','male',false,0)
,(124,'Byron','Arryn','male',false,0)
,(125,'Cadwyn','House Lannister','male',false,0)
,(126,'Caleotte','House Martell','male',false,0)
,(127,'Catelyn Tully','House Stark','female',true,299)
,(128,'Cayn','House Stark','male',false,298)
,(129,'Cellador','Night''s Watch','male',false,0)
,(130,'Cersei Frey','None','female',true,0)
,(131,'Cersei Lannister','House Lannister','female',true,0)
,(132,'Chataya','None','female',false,0)
,(133,'Chayle','Stark','male',false,299)
,(134,'Chella','Lannister','female',false,0)
,(135,'Chett','Night''s Watch','male',false,299)
,(136,'Chiggen','Lannister','male',false,298)
,(137,'Chiswyck','None','male',false,299)
,(138,'Clayton Suggs','Baratheon','male',false,0)
,(139,'Clement Piper','Tully','male',true,0)
,(140,'Cleos Frey','None','male',true,299)
,(141,'Cley Cerwyn','Stark','male',true,299)
,(142,'Clubfoot Karl','Night''s Watch','male',false,300)
,(143,'Clydas','Night''s Watch','male',false,0)
,(144,'Cohollo','None','male',false,298)
,(145,'Coldhands','None','male',false,0)
,(146,'Colemon','House Arryn','male',false,0)
,(147,'Colen of Greenpools','House Baratheon','male',true,0)
,(148,'Conn','Lannister','male',false,298)
,(149,'Conwy','Night''s Watch','male',false,0)
,(150,'Corliss Penny','Baratheon','male',false,0)
,(151,'Cortnay Penrose','Baratheon','male',true,299)
,(152,'Cotter Pyke','Night''s Watch','male',false,0)
,(153,'Cragorn','House Greyjoy','male',false,300)
,(154,'Craster','None','male',false,299)
,(155,'Cregan Karstark','Stark','male',true,0)
,(156,'Creighton Longbough','None','male',false,0)
,(157,'Cressen','Baratheon','male',false,299)
,(158,'Cuger','Night''s Watch','male',false,0)
,(159,'Cutjack','None','male',false,0)
,(160,'Daario Naharis','Targaryen','male',false,0)
,(161,'Dacey Mormont','Stark','female',true,299)
,(162,'Daemon Sand','Martell','male',false,0)
,(163,'Daenerys Targaryen','House Targaryen','female',true,0)
,(164,'Dagon Codd','Greyjoy','male',true,300)
,(165,'Dagmer','House Greyjoy','male',false,0)
,(166,'Dalbridge','Night''s Watch','male',false,299)
,(167,'Dale Seaworth','Baratheon','male',true,299)
,(168,'Dalla','Wildling','female',true,300)
,(169,'Dalla (Dragonstone)','Baratheon','female',false,0)
,(170,'Damon Dance-for-Me','None','male',false,0)
,(171,'Damon Vypren','None','male',true,0)
,(172,'Dancy','None','female',false,0)
,(173,'Danwell Frey','None','male',true,0)
,(174,'Dareon','Night''s Watch','male',false,300)
,(175,'Daryn Hornwood','Stark','male',true,298)
,(176,'Daven Lannister','House Lannister','male',true,0)
,(177,'Davos Seaworth','Baratheon','male',true,0)
,(178,'Del','Wildling','male',false,299)
,(179,'Delp','House Tully','male',false,299)
,(180,'Denys Drumm','Greyjoy','male',true,0)
,(181,'Denys Mallister','Night''s Watch','male',true,0)
,(182,'Dermot','Baratheon','male',false,0)
,(183,'Desmond','House Stark','male',false,298)
,(184,'Desmond Grell','Tully','male',true,0)
,(185,'Devan Seaworth','Baratheon','male',true,0)
,(186,'Deziel Dalt','Martell','male',true,0)
,(187,'Dhazzar','None','male',true,0)
,(188,'Dick Crabb','None','male',false,300)
,(189,'Dick Follard','Night''s Watch','male',false,299)
,(190,'Dickon Manwoody','Martell','male',true,0)
,(191,'Dirk','Night''s Watch','male',false,300)
,(192,'Dobber','None','male',false,299)
,(193,'Donal Noye','Night''s Watch','male',false,300)
,(194,'Donella Hornwood','Stark','female',true,299)
,(195,'Donnel Drumm','Greyjoy','male',true,0)
,(196,'Donnel Haigh','None','male',true,0)
,(197,'Donnel Hill','Night''s Watch','male',false,0)
,(198,'Donnel Locke','Stark','male',true,299)
,(199,'Donnel Waynwood','Tully','male',true,0)
,(200,'Donnis','House Stark','male',false,0)
,(201,'Dontos Hollard','None','male',true,300)
,(202,'Donyse','None','female',false,0)
,(203,'Doran Martell','Martell','male',true,0)
,(204,'Doreah','House Targaryen','female',false,299)
,(205,'Dornish Dilly','Night''s Watch','male',false,299)
,(206,'Draqaz','None','male',true,0)
,(207,'Drennan','House Greyjoy','male',false,299)
,(208,'Drogo','Targaryen','male',true,298)
,(209,'Dudley','Stark','male',false,299)
,(210,'Dunsen','None','male',false,0)
,(211,'Dunstan Drumm','Greyjoy','male',true,0)
,(212,'Duram Bar Emmon','Baratheon','male',true,0)
,(213,'Dykk Harlaw','Greyjoy','male',false,299)
,(214,'Dywen','Night''s Watch','male',false,0)
,(215,'Easy','Night''s Watch','male',false,300)
,(216,'Ebben','Night''s Watch','male',false,299)
,(217,'Eddard Karstark','Stark','male',true,298)
,(218,'Eddard Stark','House Stark','male',true,299)
,(219,'Eddison Tollett','Night''s Watch','male',false,0)
,(220,'Edmure Tully','House Tully','male',true,0)
,(221,'Edric Dayne','None','male',true,0)
,(222,'Edric Storm','House Baratheon','male',false,0)
,(223,'Edwyn Frey','None','male',true,0)
,(224,'Eggon','None','male',false,0)
,(225,'Elder Brother','None','male',false,0)
,(226,'Eldred Codd','Greyjoy','male',true,0)
,(227,'Eleyna Westerling','Stark','female',true,0)
,(228,'Elinor Tyrell','Tyrell','female',true,0)
,(229,'Ellaria Sand','Martell','female',true,0)
,(230,'Elmar Frey','None','male',true,0)
,(231,'Elyas Willum','Baratheon','male',true,0)
,(232,'Emmon Cuy','Baratheon','male',true,299)
,(233,'Emmon Frey','Lannister','male',true,0)
,(234,'Emmond','Greyjoy','male',false,0)
,(235,'Emrick','Night''s Watch','male',false,0)
,(236,'Endehar','Greyjoy','male',false,0)
,(237,'Elwood','House Tully','male',false,299)
,(238,'Endrew Tarth','Night''s Watch','male',false,299)
,(239,'Enger','House Tully','male',false,0)
,(240,'Eon Hunter','Arryn','male',true,300)
,(241,'Erik Ironmaker','Greyjoy','male',true,0)
,(242,'Ermesande Hayford','None','female',true,0)
,(243,'Eroeh','Targaryen','male',false,298)
,(244,'Erreck','None','male',false,0)
,(245,'Erryk (Guard)','House Tyrell','male',false,0)
,(246,'Esgred','Greyjoy','male',false,0)
,(247,'Ezzara','Targaryen','female',false,0)
,(248,'Falia Flowers','Greyjoy','female',false,0)
,(249,'Falyse Stokeworth','Lannister','female',true,300)
,(250,'Farlen','House Stark','male',false,299)
,(251,'Fat Walda Frey','None','female',true,0)
,(252,'Flement Brax','Lannister','male',true,0)
,(253,'Fletcher Will','None','male',false,299)
,(254,'Fogo','None','male',true,298)
,(255,'Forley Prester','Lannister','male',true,0)
,(256,'Fornio','Night''s Watch','male',false,0)
,(257,'Frenken','Lannister','male',false,0)
,(258,'Frenya','Wildling','female',false,300)
,(259,'Frynne','Martell','female',false,0)
,(260,'Gage','House Stark','male',true,0)
,(261,'Galazza Galare','None','female',true,0)
,(262,'Galbart Glover','Stark','male',true,0)
,(263,'Gared','Night''s Watch','male',false,297)
,(264,'Garin (Orphan)','Martell','male',false,0)
,(265,'Gariss','House Stark','male',false,0)
,(266,'Garlan Tyrell','House Tyrell','male',true,0)
,(267,'Garrett Paege','Lannister','male',true,0)
,(268,'Garse Goodbrook','None','male',true,299)
,(269,'Garth Greyfeather','Night''s Watch','male',false,300)
,(270,'Garth of Greenaway','Night''s Watch','male',false,300)
,(271,'Garth of Oldtown','Night''s Watch','male',false,299)
,(272,'Gawen Westerling','Stark','male',true,0)
,(273,'Gelmarr','House Greyjoy','male',false,299)
,(274,'Gendry','None','male',false,0)
,(275,'Genna Lannister','Lannister','female',true,0)
,(276,'Gerald Gower','Baratheon','male',true,0)
,(277,'Gerold Dayne','Martell','male',true,0)
,(278,'Gerren','None','male',false,299)
,(279,'Gerris Drinkwater','Martell','male',true,0)
,(280,'Gevin Harlaw','Greyjoy','male',true,299)
,(281,'Ghael','None','male',false,0)
,(282,'Ghost of High Heart','None','female',false,0)
,(283,'Gillam','None','male',false,0)
,(284,'Gilly','Wildling','female',false,0)
,(285,'Gilwood Hunter','Arryn','male',true,0)
,(286,'Gladden Wylde','Stark','male',true,298)
,(287,'Glendon Hewett','Night''s Watch','male',false,0)
,(288,'Goady','Night''s Watch','male',false,0)
,(289,'Godric Borrell','None','male',true,0)
,(290,'Godry Farring','Baratheon','male',true,0)
,(291,'Godwyn','House Lannister','male',false,0)
,(292,'Goghor','None','male',false,0)
,(293,'Gormond Goodbrother','Greyjoy','male',true,0)
,(294,'Gorold Goodbrother','Greyjoy','male',true,0)
,(295,'Gran Goodbrother','Greyjoy','male',true,0)
,(296,'Grazdan','None','male',true,299)
,(297,'Grazdan mo Eraz','None','male',true,0)
,(298,'Grazdan mo Ullhor','None','male',true,299)
,(299,'Grazdan zo Galare','None','male',true,0)
,(300,'Grazdar zo Galare','None','male',true,0)
,(301,'Gregor Clegane','Lannister','male',true,300)
,(302,'Grenn','Night''s Watch','male',false,0)
,(303,'Grey Worm','Targaryen','male',false,0)
,(304,'Greydon Goodbrother','Greyjoy','male',true,0)
,(305,'Grigg','Wildling','male',false,0)
,(306,'Grisel','None','female',false,0)
,(307,'Groleo','House Targaryen','male',false,300)
,(308,'Grubbs','Night''s Watch','male',false,300)
,(309,'Grunt','None','male',false,0)
,(310,'Gueren','Night''s Watch','male',false,0)
,(311,'Guncer Sunglass','Baratheon','male',true,299)
,(312,'Guyard Morrigen','Baratheon','male',true,299)
,(313,'Gwin Goodbrother','Greyjoy','female',true,0)
,(314,'Gylbert Farwynd','Greyjoy','male',true,0)
,(315,'Gyles Farwynd','Greyjoy','male',true,0)
,(316,'Gyles Grafton','Arryn','male',true,0)
,(317,'Gyles Rosby','Lannister','male',true,300)
,(318,'Gynir','House Greyjoy','male',false,299)
,(319,'Gysella Goodbrother','Greyjoy','female',true,0)
,(320,'Haggo','None','male',false,298)
,(321,'Hairy Hal','Night''s Watch','male',false,300)
,(322,'Hake','Night''s Watch','male',false,299)
,(323,'Halder','Night''s Watch','male',false,0)
,(324,'Haldon','House Targaryen','male',false,0)
,(325,'Hali','Wildling','female',false,298)
,(326,'Hallis Mollen','Stark','male',true,0)
,(327,'Hallyne','Lannister','male',false,0)
,(328,'Halys Hornwood','Stark','male',true,298)
,(329,'Hamish the Harper','None','male',false,300)
,(330,'Hareth (Mole''s Town)','Night''s Watch','male',false,0)
,(331,'Harghaz','None','male',false,300)
,(332,'Harma','Wildling','female',true,300)
,(333,'Harmund Sharp','Greyjoy','male',true,0)
,(334,'Harmune','Night''s Watch','male',false,0)
,(335,'Harra','None','female',false,299)
,(336,'Harrag Sharp','Greyjoy','male',true,299)
,(337,'Harras Harlaw','Greyjoy','male',true,0)
,(338,'Harwood Fell','House Baratheon','male',true,300)
,(339,'Hazzea','None','female',false,300)
,(340,'Harrion Karstark','Stark','male',true,0)
,(341,'Harry Strickland','None','male',false,0)
,(342,'Harwin','Stark','male',false,0)
,(343,'Harwood Stout','Stark','male',true,0)
,(344,'Harys Haigh','None','male',true,0)
,(345,'Harys Swyft','Lannister','male',true,0)
,(346,'Helman Tallhart','Stark','male',true,299)
,(347,'Henly (Maester)','None','male',false,0)
,(348,'Heward','House Stark','male',false,298)
,(349,'High Sparrow','None','male',false,0)
,(350,'Hobb','Night''s Watch','male',false,0)
,(351,'Hobber Redwyne','Tyrell','male',true,0)
,(352,'Hod','None','male',false,0)
,(353,'Hodor','House Stark','male',false,0)
,(354,'Holger','None','male',false,0)
,(355,'Holly','Wildling','female',false,300)
,(356,'Hop-Robin','Night''s Watch','male',false,0)
,(357,'Horas Redwyne','Tyrell','male',true,0)
,(358,'Horton Redfort','Arryn','male',true,0)
,(359,'Hosteen Frey','None','male',true,0)
,(360,'Hoster Tully','House Tully','male',true,299)
,(361,'Hot Pie','None','male',false,0)
,(362,'Hother Umber','Stark','male',true,0)
,(363,'Howd Wanderer','Wildling','male',true,0)
,(364,'Hubard Rambton','Baratheon','male',true,299)
,(365,'Hugh','House Arryn','male',false,298)
,(366,'Hugo Vance','Tully','male',true,0)
,(367,'Hullen','House Stark','male',false,298)
,(368,'Humfrey Swyft','Lannister','male',true,0)
,(369,'Husband','None','male',false,0)
,(370,'Hyle Hunt','None','male',true,300)
,(371,'Iggo','None','male',false,299)
,(372,'Illyrio Mopatis','House Targaryen','male',true,0)
,(373,'Ilyn Payne','Lannister','male',true,0)
,(374,'Imry Florent','Baratheon','male',true,299)
,(375,'Iron Emmett','Night''s Watch','male',false,0)
,(376,'Irri','House Targaryen','female',false,0)
,(377,'Ithoke','None','male',false,0)
,(378,'Jacelyn Bywater','Lannister','female',true,299)
,(379,'Jack Bulwer','Night''s Watch','male',false,300)
,(380,'Jack-Be-Lucky','None','male',false,0)
,(381,'Jacks','House Stark','male',false,0)
,(382,'Jaggot','None','male',false,0)
,(383,'Jaime Lannister','Lannister','male',true,0)
,(384,'Jalabhar Xho','None','male',true,0)
,(385,'Janna Tyrell','Tyrell','female',true,0)
,(386,'Janos Slynt','None','male',true,300)
,(387,'Jaqen H''ghar','None','male',false,0)
,(388,'Jared Frey','None','male',true,300)
,(389,'Jaremy Rykker','Night''s Watch','male',true,298)
,(390,'Jarl','Wildling','male',false,299)
,(391,'Jarman Buckwell','Night''s Watch','male',false,300)
,(392,'Jason Mallister','Stark','male',true,0)
,(393,'Jate','House Lannister','male',false,0)
,(394,'Jate Blackberry','House Baratheon','male',false,0)
,(395,'Jeor Mormont','Night''s Watch','male',true,299)
,(396,'Jeren','Night''s Watch','male',false,0)
,(397,'Jeyne Poole','Stark','female',true,0)
,(398,'Jeyne Westerling','Stark','female',true,0)
,(399,'Jhaqo','None','male',true,0)
,(400,'Jhezane','None','female',true,0)
,(401,'Jhiqui','House Targaryen','female',false,0)
,(402,'Jhogo','House Targaryen','male',false,0)
,(403,'Jocelyn Swyft','Lannister','female',true,0)
,(404,'Jodge','House Lannister','male',false,0)
,(405,'Jojen Reed','Stark','male',true,0)
,(406,'Jommy','House Baratheon','male',false,0)
,(407,'Jon Bettley','Lannister','male',true,0)
,(408,'Jon Connington','Targaryen','male',true,0)
,(409,'Jon Fossoway','Baratheon','male',true,0)
,(410,'Jon Snow','Night''s Watch','male',true,0)
,(411,'Jon Umber (Greatjon)','Stark','male',true,0)
,(412,'Joffrey Baratheon','House Lannister','male',true,300)
,(413,'Jon Umber (Smalljon)','Stark','male',true,299)
,(414,'Jonelle Cerwyn','Stark','female',true,0)
,(415,'Jonos Bracken','Tully','male',true,0)
,(416,'Jorah Mormont','Targaryen','male',true,0)
,(417,'Jory Cassel','Stark','male',true,298)
,(418,'Joseran','Greyjoy','male',false,0)
,(419,'Joseth','House Stark','male',false,0)
,(420,'Josmyn Peckledon','Lannister','male',false,0)
,(421,'Joss','None','male',false,0)
,(422,'Joss Stilwood','Lannister','male',false,0)
,(423,'Josua Willum','Baratheon','male',true,0)
,(424,'Jothos Slynt','Lannister','male',true,0)
,(425,'Joyeuse Erenford','None','female',true,0)
,(426,'Justin Massey','Baratheon','male',true,0)
,(427,'Jyck','House Lannister','male',false,298)
,(428,'Jynessa Blackmont','Martell','female',true,0)
,(429,'Karyl Vance','Tully','male',true,0)
,(430,'Kedge Whiteye','Night''s Watch','male',false,0)
,(431,'Kella','None','female',false,0)
,(432,'Kennos of Kayce','Lannister','male',true,0)
,(433,'Ketter','Night''s Watch','male',false,0)
,(434,'Kenned','House Greyjoy','male',false,299)
,(435,'Kerwin','House Tyrell','male',false,300)
,(436,'Kevan Lannister','House Lannister','male',true,300)
,(437,'Kezmya','None','female',true,0)
,(438,'Khorane Sathmantes','None','male',false,0)
,(439,'Khrazz','None','male',false,300)
,(440,'Kindly man','None','male',false,0)
,(441,'Kojja Mo','None','female',false,0)
,(442,'Koss','Night''s Watch','male',false,299)
,(443,'Kraznys mo Nakloz','None','male',true,299)
,(444,'Kromm','House Greyjoy','male',false,299)
,(445,'Kurleket','None','male',false,298)
,(446,'Kurz','Night''s Watch','male',false,299)
,(447,'Kyle (Banners)','None','male',false,299)
,(448,'Kyra','House Stark','female',false,300)
,(449,'Lady of the Leaves','None','female',false,0)
,(450,'Lambert Turnberry','Lannister','male',true,0)
,(451,'Lamprey','Baratheon','male',false,0)
,(452,'Lancel Lannister','Lannister','male',true,0)
,(453,'Lanna (Happy Port)','None','female',false,0)
,(454,'Lark','Night''s Watch','male',false,299)
,(455,'Larra Blackmont','Martell','female',true,0)
,(456,'Larraq','Targaryen','male',false,0)
,(457,'Leathers','Night''s Watch','male',false,0)
,(458,'Left Hand Lew','Night''s Watch','male',false,0)
,(459,'Lem','None','male',false,0)
,(460,'Lennocks','None','male',false,0)
,(461,'Lenwood Tawney','Greyjoy','male',false,0)
,(462,'Leo Lefford','Lannister','male',true,299)
,(463,'Leo Tyrell','Tyrell','male',true,0)
,(464,'Leobald Tallhart','Stark','male',true,299)
,(465,'Leona Woolfield','Stark','female',true,0)
,(466,'Leonette Fossoway','Tyrell','female',true,0)
,(467,'Lew','House Stark','male',false,0)
,(468,'Lewis Lanster','None','male',false,0)
,(469,'Lewys Lydden','Lannister','male',true,0)
,(470,'Lewys Piper','Lannister','male',true,0)
,(471,'Lharys','Stark','male',true,298)
,(472,'Little Walder Frey','None','male',true,300)
,(473,'Lollys Stokeworth','Lannister','female',true,0)
,(474,'Lommy','Night''s Watch','male',false,299)
,(475,'Loras Tyrell','Tyrell','male',true,0)
,(476,'Lorcas','None','male',false,0)
,(477,'Lord of Bones','Wildling','male',true,300)
,(478,'Lorent Caswell','Baratheon','male',true,0)
,(479,'Lorren','Greyjoy','male',false,299)
,(480,'Lothar Frey','None','male',true,0)
,(481,'Lothor Brune','None','male',true,0)
,(482,'Lucan','None','male',false,299)
,(483,'Lucas Blackwood','Tully','male',true,299)
,(484,'Lucas Codd','Greyjoy','male',true,0)
,(485,'Lucias Vypren','None','male',true,0)
,(486,'Luco Prestayn','None','male',false,0)
,(487,'Luke of Longtown','Night''s Watch','male',false,0)
,(488,'Luton','None','male',false,300)
,(489,'Luwin','House Stark','male',false,299)
,(490,'Lyle Crakehall','Lannister','male',true,0)
,(491,'Lyman Darry','Tully','male',true,299)
,(492,'Lymond Goodbrook','Tully','male',true,0)
,(493,'Lymond Lychester','Tully','male',true,0)
,(494,'Lyn Corbray','Arryn','male',true,0)
,(495,'Lyonel','None','male',false,0)
,(496,'Lysa Tully','House Arryn','female',true,300)
,(497,'Lysono Maar','None','male',false,0)
,(498,'Mace Tyrell','House Tyrell','male',true,0)
,(499,'Mad Huntsman','None','male',false,0)
,(500,'Maege Mormont','Stark','female',true,0)
,(501,'Maerie (Goodwife)','None','female',false,299)
,(502,'Maerie (Whore)','None','female',false,299)
,(503,'Mag Mar Tun Doh Weg','Wildling','male',true,300)
,(504,'Mago','None','male',false,0)
,(505,'Mallador Locke','Night''s Watch','male',false,299)
,(506,'Malliard','Lannister','male',false,0)
,(507,'Mallor','House Lannister','male',false,0)
,(508,'Mance Rayder','Wildling','male',true,0)
,(509,'Mandon Moore','Baratheon','male',true,299)
,(510,'Maric Seaworth','House Baratheon','male',true,299)
,(511,'Marei','None','female',false,0)
,(512,'Margaery Tyrell','House Tyrell','female',true,0)
,(513,'Marillion','Arryn','male',false,300)
,(514,'Maris','Wildling','female',false,0)
,(515,'Marissa Frey','None','female',true,0)
,(516,'Mariya Darry','None','female',true,0)
,(517,'Mark Mullendore','Tully','male',true,0)
,(518,'Marlon Manderly','Stark','male',true,0)
,(519,'Maron Volmark','Greyjoy','male',true,0)
,(520,'Marq Piper','Tully','male',true,0)
,(521,'Martyn Rivers','None','male',true,0)
,(522,'Marwyn','None','male',false,0)
,(523,'Marwyn Belmore','Arryn','male',true,0)
,(524,'Masha Heddle','Tully','female',false,298)
,(525,'Maslyn','Night''s Watch','male',false,299)
,(526,'Mathis Rowan','Lannister','male',true,0)
,(527,'Mathos Mallarawan','None','male',true,0)
,(528,'Matrice','Baratheon','female',false,0)
,(529,'Matthos Seaworth','Baratheon','male',true,299)
,(530,'Matthar','Night''s Watch','male',false,0)
,(531,'Mawney','Night''s Watch','male',false,300)
,(532,'Mebble','None','male',false,0)
,(533,'Medger Cerwyn','Stark','male',true,299)
,(534,'Meera Reed','Stark','female',true,0)
,(535,'Megga Tyrell','House Tyrell','female',true,0)
,(536,'Meha','Wildling','female',false,0)
,(537,'Mela','House Arryn','female',false,0)
,(538,'Meldred Merlyn','Greyjoy','male',true,0)
,(539,'Meliana','Stark','female',false,0)
,(540,'Melisandre','Baratheon','female',false,0)
,(541,'Mellei','House Martell','female',false,0)
,(542,'Melly','None','female',false,0)
,(543,'Meredyth Crane','Tyrell','female',true,0)
,(544,'Meribald','None','male',false,0)
,(545,'Merlon Crakehall','Lannister','male',true,0)
,(546,'Mero','None','male',false,299)
,(547,'Merrett Frey','None','male',true,300)
,(548,'Meryn Trant','Lannister','male',true,0)
,(549,'Mezzara','None','female',true,0)
,(550,'Mikken','House Stark','male',false,299)
,(551,'Miklaz','None','male',true,0)
,(552,'Mirri Maz Duur','None','female',false,299)
,(553,'Missandei','House Targaryen','female',false,0)
,(554,'Mohor','None','male',true,298)
,(555,'Mollander','None','male',false,0)
,(556,'Monford Velaryon','Baratheon','male',true,299)
,(557,'Monster','Wildling','male',false,0)
,(558,'Moon Boy','Baratheon','male',false,0)
,(559,'Moqorro','Greyjoy','male',false,0)
,(560,'Mord','House Arryn','male',false,0)
,(561,'Mordane','House Stark','female',false,298)
,(562,'Moreo Tumitis','None','male',false,0)
,(563,'Morgarth','None','male',false,0)
,(564,'Morna White Mask','Wildling','female',true,0)
,(565,'Moro','None','male',true,0)
,(566,'Morra','House Martell','female',false,0)
,(567,'Morrec','House Lannister','male',false,298)
,(568,'Morros Slynt','Lannister','male',true,0)
,(569,'Mors Manwoody','Martell','male',true,0)
,(570,'Mors Umber','Stark','male',true,0)
,(571,'Morton Waynwood','Arryn','male',true,0)
,(572,'Mudge (miller)','None','male',false,299)
,(573,'Mully','Night''s Watch','male',false,0)
,(574,'Munciter','Lannister','male',false,0)
,(575,'Murch','Night''s Watch','male',false,0)
,(576,'Murch (Winterfell)','House Stark','male',false,0)
,(577,'Mossador','House Targaryen','male',false,300)
,(578,'Murenmure','Greyjoy','male',false,0)
,(579,'Muttering Bill','Night''s Watch','male',false,300)
,(580,'Mya Stone','Arryn','female',false,0)
,(581,'Mycah','Stark','male',false,298)
,(582,'Myles','House Martell','male',false,0)
,(583,'Myles Manwoody','Martell','male',true,0)
,(584,'Myranda Royce','Arryn','female',true,0)
,(585,'Myrcella Baratheon','Lannister','female',true,0)
,(586,'Myria Jordayne','Martell','female',false,0)
,(587,'Myrtle','Wildling','female',false,300)
,(588,'Nage','None','male',false,0)
,(589,'Myles','House Tully','male',false,299)
,(590,'Nan','House Stark','female',false,0)
,(591,'Narbert','None','male',false,0)
,(592,'Nestor Royce','Arryn','male',true,0)
,(593,'Nolla','None','female',false,299)
,(594,'Norjen','Greyjoy','male',false,0)
,(595,'Nurse','None','male',false,300)
,(596,'Notch','None','male',false,0)
,(597,'Nute','House Greyjoy','male',false,0)
,(598,'Nymella Toland','Martell','female',true,0)
,(599,'Nymeria Sand','House Martell','female',true,0)
,(600,'Obara Sand','House Martell','female',true,0)
,(601,'Oberyn Martell','House Martell','male',true,300)
,(602,'Ogo','None','male',true,298)
,(603,'Old Henly','Night''s Watch','male',false,299)
,(604,'Olenna Redwyne','Tyrell','female',true,0)
,(605,'Ollo Lophand','Night''s Watch','male',false,300)
,(606,'Olyvar Frey','None','male',true,0)
,(607,'Ondrew Locke','Stark','male',true,0)
,(608,'Oppo','None','male',false,300)
,(609,'Orell','Wildling','male',false,299)
,(610,'Orphan Oss','Night''s Watch','male',false,300)
,(611,'Orton Merryweather','Lannister','male',true,0)
,(612,'Osfryd Kettleblack','Lannister','male',true,0)
,(613,'Osha','House Stark','female',false,0)
,(614,'Osmund Kettleblack','Lannister','male',true,0)
,(615,'Osney Kettleblack','Lannister','male',true,0)
,(616,'Ossy','Arryn','male',false,0)
,(617,'Oswell Kettleblack','None','male',true,0)
,(618,'Othell Yarwyck','Night''s Watch','male',false,0)
,(619,'Ottyn Wythers','Night''s Watch','male',false,299)
,(620,'Owen','Night''s Watch','male',false,0)
,(621,'Owen Norrey','Tully','male',true,299)
,(622,'Oznak zo Pahl','None','male',true,299)
,(623,'Palla','House Stark','female',false,0)
,(624,'Parmen Crane','Baratheon','male',true,0)
,(625,'Patchface','Baratheon','male',false,0)
,(626,'Pate (novice)','None','male',false,300)
,(627,'Pate (Lancewood)','None','male',false,299)
,(628,'Pate (Night''s Watch)','Night''s Watch','male',false,0)
,(629,'Pate (Old)','None','male',false,0)
,(630,'Patrek of King''s Mountain','Baratheon','male',true,300)
,(631,'Patrek Mallister','Tully','male',true,0)
,(632,'Paxter Redwyne','Tyrell','male',true,0)
,(633,'Pello','None','male',false,0)
,(634,'Penny','None','female',false,0)
,(635,'Perros Blackmont','Martell','male',true,0)
,(636,'Perwyn Frey','None','male',true,0)
,(637,'Petyr Baelish','None','male',false,0)
,(638,'Petyr Frey','None','male',true,300)
,(639,'Philip Foote','Lannister','male',true,0)
,(640,'Pia','None','female',false,0)
,(641,'Podrick Payne','Lannister','male',true,0)
,(642,'Polliver','None','male',false,300)
,(643,'Pono','None','male',true,0)
,(644,'Porridge','Baratheon','male',false,0)
,(645,'Porther','House Stark','male',false,299)
,(646,'Poul Pemford','House Tully','male',false,299)
,(647,'Poxy Tym','House Stark','male',false,299)
,(648,'Praed','None','male',false,299)
,(649,'Prendahl na Ghezn','None','male',false,299)
,(650,'Preston Greenfield','Baratheon','male',false,299)
,(651,'Pyat Pree','None','male',true,0)
,(652,'Pycelle','House Lannister','male',false,300)
,(653,'Pyg','None','male',false,300)
,(654,'Pylos','Baratheon','male',false,0)
,(655,'Pypar','Night''s Watch','male',false,0)
,(656,'Qarl Shepherd','Greyjoy','male',false,0)
,(657,'Qarl the Maid','Greyjoy','male',false,0)
,(658,'Qezza','None','female',false,0)
,(659,'Qhorin Halfhand','Night''s Watch','male',false,299)
,(660,'Qotho','None','male',false,298)
,(661,'Quaithe','None','female',true,0)
,(662,'Quaro','Targaryen','male',false,298)
,(663,'Quellon Humble','Greyjoy','male',true,0)
,(664,'Quent','House Stark','male',false,0)
,(665,'Quenten Banefort','Lannister','male',true,0)
,(666,'Quentyn Martell','Martell','male',true,300)
,(667,'Quhuru Mo','None','male',false,0)
,(668,'Qyburn','Lannister','male',false,0)
,(669,'Quort','Wildling','male',false,299)
,(670,'Qyle','Night''s Watch','male',false,299)
,(671,'Rafford','None','male',false,0)
,(672,'Ragnor Pyke','House Greyjoy','male',false,0)
,(673,'Ragwyle','Wildling','female',false,0)
,(674,'Rakharo','House Targaryen','male',false,0)
,(675,'Ralf Kenning','Greyjoy','male',false,300)
,(676,'Ralf Stonehouse','Greyjoy','male',true,0)
,(677,'Ralf the Limper','Greyjoy','male',false,0)
,(678,'Ramsay Snow','None','male',true,0)
,(679,'Randa','None','female',false,299)
,(680,'Randyll Tarly','Tyrell','male',true,0)
,(681,'Rast','Night''s Watch','male',false,299)
,(682,'Ravella Swann','Tully','female',true,0)
,(683,'Raymar Royce','Arryn','male',true,0)
,(684,'Raymun Darry','Targaryen','male',true,298)
,(685,'Raymund Frey','None','male',true,0)
,(686,'Raynald Westerling','Stark','male',true,299)
,(687,'Red Alyn','Night''s Watch','male',false,300)
,(688,'Red Rolfe','House Greyjoy','male',false,299)
,(689,'Reek','None','male',false,299)
,(690,'Renly Baratheon','House Baratheon','male',true,299)
,(691,'Reysen','Night''s Watch','male',false,0)
,(692,'Reznak mo Reznak','None','male',true,0)
,(693,'Rhaegar Frey','None','male',true,300)
,(694,'Rhogoro','None','male',true,0)
,(695,'Ricasso','House Martell','male',false,0)
,(696,'Richard Horpe','Baratheon','male',true,0)
,(697,'Rickard Karstark','Stark','male',true,299)
,(698,'Rickard Ryswell','Stark','male',true,0)
,(699,'Rickon Stark','House Stark','male',true,0)
,(700,'Rigney','None','male',false,0)
,(701,'Robar Royce','Baratheon','male',true,299)
,(702,'Robb Stark','House Stark','male',true,299)
,(703,'Robert Baratheon','House Baratheon','male',true,298)
,(704,'Robert Arryn','House Arryn','male',true,0)
,(705,'Robett Glover','Stark','male',true,0)
,(706,'Robin Flint','Stark','male',true,299)
,(707,'Robin Moreland','Lannister','male',true,0)
,(708,'Robin Ryger','Tully','male',true,0)
,(709,'Rodrik Cassel','Stark','male',true,299)
,(710,'Rodrik Harlaw','Greyjoy','male',true,0)
,(711,'Rodrik Ryswell','None','male',true,0)
,(712,'Roger Hogg','Lannister','male',true,0)
,(713,'Roger Ryswell','Stark','male',true,0)
,(714,'Roland Crakehall (Lord)','Lannister','male',true,0)
,(715,'Rolder','House Lannister','male',false,0)
,(716,'Rolfe','Greyjoy','male',false,0)
,(717,'Rollam Westerling','Stark','male',true,0)
,(718,'Rolfe the Dwarf','House Greyjoy','male',false,300)
,(719,'Rolley','Night''s Watch','male',false,299)
,(720,'Rolly Duckfield','Targaryen','male',false,0)
,(721,'Rolph Spicer','Lannister','male',true,0)
,(722,'Romny Weaver','Greyjoy','male',true,0)
,(723,'Ronald Storm','None','male',false,0)
,(724,'Ronnel Harclay','Night''s Watch','male',true,0)
,(725,'Ronnet Connington','Baratheon','male',true,0)
,(726,'Roose Bolton','Stark','male',true,0)
,(727,'Roose Ryswell','None','male',true,0)
,(728,'Rorge','None','male',false,300)
,(729,'Roslin Frey','None','female',true,0)
,(730,'Rowan','Wildling','male',false,300)
,(731,'Rudge','Night''s Watch','male',false,0)
,(732,'Rusty Flowers','Night''s Watch','male',false,0)
,(733,'Ryger Rivers','None','male',false,0)
,(734,'Ryk','Wildling','male',false,0)
,(735,'Rupert Brax','House Lannister','male',false,299)
,(736,'Ryman Frey','None','male',true,300)
,(737,'Rymolf Stormdrunk','House Greyjoy','male',false,0)
,(738,'Ryon Allyrion','Martell','male',true,0)
,(739,'Salladhor Saan','Baratheon','male',true,0)
,(740,'Sallor','None','male',false,299)
,(741,'Samwell Tarly','Night''s Watch','male',true,0)
,(742,'Sandor Clegane','None','male',true,300)
,(743,'Sawane Botley','Greyjoy','male',true,299)
,(744,'Sansa Stark','Stark','female',true,0)
,(745,'Sarella Sand','House Martell','female',false,0)
,(746,'Sarra Frey','None','female',true,0)
,(747,'Satin','Night''s Watch','male',false,0)
,(748,'Sawwood','Night''s Watch','male',false,0)
,(749,'Sedgekins','None','male',false,0)
,(750,'Selyse Florent','Baratheon','female',true,0)
,(751,'Senelle','House Lannister','female',false,300)
,(752,'Serra Frey','None','female',true,0)
,(753,'Shadrich','None','male',false,0)
,(754,'Shae','Lannister','female',false,300)
,(755,'Shagga','Lannister','male',false,0)
,(756,'Shagwell','None','male',false,300)
,(757,'Sharna','None','female',false,0)
,(758,'Shireen Baratheon','Baratheon','female',true,0)
,(759,'Shirei Frey','None','female',true,0)
,(760,'Shyra Errol','Baratheon','female',true,300)
,(761,'Sigfry Stonetree','Greyjoy','male',true,0)
,(762,'Skahaz mo Kandaq','None','male',true,0)
,(763,'Skinner','None','male',false,0)
,(764,'Small Paul','Night''s Watch','male',false,299)
,(765,'Softfoot','Night''s Watch','male',false,299)
,(766,'Sour Alyn','None','male',false,0)
,(767,'Spare Boot','Night''s Watch','male',false,0)
,(768,'Spotted Cat','None','male',false,0)
,(769,'Spotted Pate of Maidenpool','Night''s Watch','male',false,299)
,(770,'Squint','House Greyjoy','male',false,299)
,(771,'Squirrel','Wildling','female',false,300)
,(772,'Stalwart Shield','Targaryen','male',false,300)
,(773,'Steelskin','None','male',false,0)
,(774,'Steffon Swyft','Lannister','male',true,0)
,(775,'Stevron Frey','Stark','male',true,299)
,(776,'Stiv','Wildling','male',false,298)
,(777,'Stone Thumbs','Wildling','male',false,299)
,(778,'Stonesnake','Night''s Watch','male',false,0)
,(779,'Stygg','House Greyjoy','male',false,0)
,(780,'Styr','Wildling','male',true,300)
,(781,'Sybassion','None','male',false,0)
,(782,'Sybell Spicer','Lannister','female',true,0)
,(783,'Sybelle Glover','Stark','female',true,0)
,(784,'Sylva Santagar','Martell','female',true,0)
,(785,'Symon Silver Tongue','Lannister','male',false,299)
,(786,'Symon Stripeback','Targaryen','male',false,0)
,(787,'Symond Frey','None','male',true,300)
,(788,'Symond Templeton','Arryn','male',true,0)
,(789,'Syrio Forel','House Stark','male',false,298)
,(790,'Taena of Myr','Lannister','female',true,0)
,(791,'Tal Toraq','Targaryen','male',false,0)
,(792,'Tallad','Lannister','male',false,0)
,(793,'Tanda Stokeworth','Lannister','female',true,300)
,(794,'Tanton Fossoway','Baratheon','male',true,0)
,(795,'Ternesio Terys','None','male',false,0)
,(796,'Terrance Lynderly','Arryn','male',true,0)
,(797,'The Red Lamb','House Targaryen','male',false,0)
,(798,'Theo Frey','None','male',true,0)
,(799,'Theodan Wells','Stark','male',true,0)
,(800,'Theomore Lannister','None','male',true,0)
,(801,'Theon Greyjoy','House Greyjoy','male',true,0)
,(802,'Thistle','Wildling','female',false,300)
,(803,'Thoren Smallwood','Night''s Watch','male',true,299)
,(804,'Thoros','None','male',false,0)
,(805,'Three Toes','None','male',false,0)
,(806,'Three-Tooth','Greyjoy','female',false,0)
,(807,'Tickler','Lannister','male',false,300)
,(808,'Tim Tangletongue','Night''s Watch','male',false,0)
,(809,'Timeon','None','male',false,300)
,(810,'Timett','Lannister','male',false,0)
,(811,'Timon','Baratheon','male',false,0)
,(812,'Tion Frey','Lannister','female',true,299)
,(813,'Tobho Mott','None','male',false,0)
,(814,'Todder','Night''s Watch','male',false,0)
,(815,'Todric','Greyjoy','male',false,299)
,(816,'Tom of Sevenstreams','None','male',false,0)
,(817,'Tomard','House Stark','male',false,298)
,(818,'Tormund','Wildling','male',true,0)
,(819,'Torrek','None','male',false,0)
,(820,'Torrhen Karstark','Stark','male',true,298)
,(821,'Tothmure','Lannister','male',false,299)
,(822,'Tregar','House Lannister','male',false,298)
,(823,'Tremond Gargalen','Martell','male',true,0)
,(824,'Tristifer Botley','Greyjoy','male',true,0)
,(825,'Triston Sunderland','Lannister','male',true,0)
,(826,'Tuffleberry','None','male',false,0)
,(827,'Tumberjon','Night''s Watch','male',false,0)
,(828,'Tumco Lho','Targaryen','male',false,0)
,(829,'Tybero Istarion','None','male',false,0)
,(830,'Tycho Nestoris','None','male',false,0)
,(831,'Tyene Sand','House Martell','female',true,0)
,(832,'Tymor','House Greyjoy','male',false,299)
,(833,'Tyrek Lannister','House Lannister','male',true,299)
,(834,'Tyrion Lannister','Lannister','male',true,0)
,(835,'Tyta Frey','None','female',true,0)
,(836,'Tytos Blackwood','Tully','male',true,0)
,(837,'Tytos Brax','Lannister','male',true,0)
,(838,'Tytos Frey','None','male',true,299)
,(839,'Tywin Lannister','House Lannister','male',true,300)
,(840,'Ulf son of Umar','Lannister','male',false,298)
,(841,'Ulf the Ill','House Greyjoy','male',false,299)
,(842,'Ulmer','Night''s Watch','male',false,0)
,(843,'Ulwyck Uller','Martell','male',true,0)
,(844,'Umar','None','male',false,0)
,(845,'Umfred','None','male',false,0)
,(846,'Unella','None','male',false,0)
,(847,'Urreg','Night''s Watch','male',false,299)
,(848,'Urswyck','None','male',false,0)
,(849,'Utherydes Wayn','Tully','male',false,0)
,(850,'Utt','None','male',false,299)
,(851,'Val','Wildling','female',false,0)
,(852,'Varamyr','Wildling','male',false,300)
,(853,'Vardis Egen','Arryn','male',false,298)
,(854,'Vargo Hoat','None','male',false,300)
,(855,'Varys','Targaryen','male',false,0)
,(856,'Vayon Poole','Stark','male',false,298)
,(857,'Victarion Greyjoy','House Greyjoy','male',true,0)
,(858,'Viserys Targaryen','House Targaryen','male',true,298)
,(859,'Vylarr','House Lannister','male',false,0)
,(860,'Vyman','Tully','male',false,0)
,(861,'Waif','None','female',false,0)
,(862,'Walda Rivers (daughter of Aemon)','None','female',true,0)
,(863,'Walder Frey','None','male',true,0)
,(864,'Walder Rivers','None','male',true,0)
,(865,'Wallen','Wildling','male',false,298)
,(866,'Walton','None','male',false,0)
,(867,'Wat (orphan)','None','male',false,0)
,(868,'Wat (sailor)','None','male',false,0)
,(869,'Watt','Night''s Watch','male',false,299)
,(870,'Watty','None','male',false,0)
,(871,'Waymar Royce','Night''s Watch','male',true,297)
,(872,'Wayn (guard)','House Stark','male',false,0)
,(873,'Weasel','None','female',false,0)
,(874,'Weeper','Wildling','male',true,0)
,(875,'Weese','Lannister','male',false,299)
,(876,'Wendel Manderly','Stark','male',true,299)
,(877,'Wendello Qar Deeth','None','male',true,0)
,(878,'Werlag','House Greyjoy','male',false,299)
,(879,'Wex Pyke','Stark','male',false,0)
,(880,'Whalen Frey','None','male',true,0)
,(881,'Wilbert','Stark','male',false,298)
,(882,'Will','Night''s Watch','male',false,297)
,(883,'Will (orphan)','None','male',false,0)
,(884,'Willam Wells','Martell','male',false,300)
,(885,'Willem Lannister','House Lannister','male',true,299)
,(886,'William Mooton','Tully','male',true,0)
,(887,'Willis Wode','Arryn','male',true,0)
,(888,'Willit','Lannister','male',false,0)
,(889,'Willow Witch-eye','Wildling','female',false,300)
,(890,'Willum','Tully','male',false,0)
,(891,'Woth','Night''s Watch','male',false,299)
,(892,'Wulfe','House Greyjoy','male',false,0)
,(893,'Wun Weg Wun Dar Wun','Wildling','male',false,0)
,(894,'Wyl (guard)','House Stark','male',false,298)
,(895,'Wyl the Whittler','None','male',false,299)
,(896,'Wylis Manderly','Stark','male',true,0)
,(897,'Wylla Manderly','Stark','female',true,0)
,(898,'Wyman Manderly','Stark','male',true,0)
,(899,'Wynafryd Manderly','Stark','male',true,0)
,(900,'Wynton Stout','Night''s Watch','male',false,0)
,(901,'Xaro Xhoan Daxos','None','male',true,0)
,(902,'Xhondo','None','male',false,0)
,(903,'Yandry','House Targaryen','male',false,0)
,(904,'Yellow Dick','None','male',false,300)
,(905,'Ygon Farwynd','Greyjoy','male',true,0)
,(906,'Ygritte','Wildling','female',false,299)
,(907,'Yohn Farwynd','Greyjoy','male',true,0)
,(908,'Yohn Royce','Arryn','male',true,0)
,(909,'Yoren','Night''s Watch','male',false,299)
,(910,'Young Henly','Night''s Watch','male',false,299)
,(911,'Ysilla','House Targaryen','male',false,0)
,(912,'Zei','Stark','female',false,0)
,(913,'Zollo','None','male',false,0)
,(914,'Yurkhaz zo Yunzak','None','male',false,300)
,(915,'Yezzan Zo Qaggaz','None','male',true,300)
,(916,'Torwynd the Tame','Wildling','male',false,300)
,(917,'Talbert Serry','Tyrell','male',true,300);
